spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: review_db
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
      max-lifetime: 10000
      idle-timeout: 30000
      connection-timeout: 10000
      pool-name: HikariPool
server:
  port: 8088

